<<<<<<< HEAD
[INFO] 2019-01-06 15:30:04,756 >>	[START]  Processor.process_train()
[INFO] 2019-01-06 15:30:04,757 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-06 15:30:05,208 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[ERROR] 2019-01-06 15:30:05,251 >>	Unexpected Exception Occurred.
=======
[INFO] 2019-01-06 14:23:09,197 >>	[START]  Processor.process_train()
[INFO] 2019-01-06 14:23:09,197 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-06 14:23:09,557 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[ERROR] 2019-01-06 14:23:09,557 >>	Unexpected Exception Occurred.
>>>>>>> a8d8db93f8ce2235084603e0e9e9d5d68557b824
Traceback (most recent call last):
  File "src/main.py", line 18, in <module>
    main(get_option())
  File "src/main.py", line 10, in main
    ProcessorFactory.process(args)
  File "/Users/berry/Kaggle/malware/src/processor_factory.py", line 32, in process
    validity, predict = processor.process()
  File "/Users/berry/Kaggle/malware/src/processor.py", line 26, in process
    validity = self.__process_train()
  File "/Users/berry/Kaggle/malware/src/save_log.py", line 80, in wrapper
    result = func(*args, **kargs)
<<<<<<< HEAD
  File "/home/icebee/project/Malware/src/processor.py", line 44, in __process_train
=======
  File "/Users/berry/Kaggle/malware/src/processor.py", line 43, in __process_train
>>>>>>> a8d8db93f8ce2235084603e0e9e9d5d68557b824
    assert False
AssertionError
