[INFO] 2019-01-13 01:18:17,135 >>	[START]  Processor.preprocess()
[INFO] 2019-01-13 01:18:17,136 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:18:17,166 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:18:17,167 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 01:18:17,188 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-01-13 01:18:17,190 >>	[START]  FeatureExtractor.extract()
[ERROR] 2019-01-13 01:18:20,075 >>	Unexpected Exception Occurred.
Traceback (most recent call last):
  File "src/main.py", line 20, in <module>
    main(get_option())
  File "src/main.py", line 12, in main
    ProcessorFactory.process(args)
  File "/home/icebee/project/Malware/src/processor_factory.py", line 32, in process
    validity, predict = processor.process()
  File "/home/icebee/project/Malware/src/processor.py", line 32, in process
    feature_names = self.__preprocess()
  File "/home/icebee/project/Malware/src/save_log.py", line 83, in wrapper
    result = func(*args, **kargs)
  File "/home/icebee/project/Malware/src/processor.py", line 70, in __preprocess
    feature_extractor.extract(part="test", valid_dir=valid_dir)
  File "/home/icebee/project/Malware/src/save_log.py", line 83, in wrapper
    result = func(*args, **kargs)
  File "/home/icebee/project/Malware/src/feature_extractor.py", line 38, in extract
    feature_dict[group] = group_feature_instance.extract()
  File "/home/icebee/project/Malware/features/Categorical.py", line 71, in extract
    return super().extract()
  File "/home/icebee/project/Malware/features/base_feature.py", line 63, in extract
    new_feature_df = eval(formula[0], locals())
  File "<string>", line 1, in <module>
  File "/home/icebee/project/Malware/features/Categorical.py", line 84, in LabelEncoding
    usecols=cols)
  File "/home/icebee/.local/share/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/icebee/.local/share/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/icebee/.local/share/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/icebee/.local/share/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/icebee/.local/share/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'/home/icebee/project/Malware/data/subset/min/train.csv' does not exist
