[INFO] 2019-02-20 22:30:05,174 >>	Classifier Type: PYTORCH
[INFO] 2019-02-20 22:30:05,174 >>	Input Path: /media/mocobt/Volume/Kaggle/Malware/data/subset/min
[INFO] 2019-02-20 22:30:05,175 >>	--------------------------------
[INFO] 2019-02-20 22:30:05,176 >>	[START]  Processor.preprocess()
[INFO] 2019-02-20 22:30:05,177 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-02-20 22:30:05,292 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-02-20 22:30:05,296 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-02-20 22:30:05,333 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-02-20 22:30:05,337 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-02-20 22:30:05,355 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-02-20 22:30:05,356 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-02-20 22:30:05,387 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-02-20 22:30:05,389 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-02-20 22:30:05,420 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-02-20 22:30:05,421 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-02-20 22:30:05,451 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-02-20 22:30:05,454 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-02-20 22:30:05,493 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-02-20 22:30:05,495 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-02-20 22:30:05,524 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-02-20 22:30:05,527 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-02-20 22:30:05,556 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-02-20 22:30:05,558 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-02-20 22:30:05,587 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 00:00:00
[INFO] 2019-02-20 22:30:05,588 >>	[FINISH] Processor.preprocess(): [elapsed_time] >> 00:00:00
[INFO] 2019-02-20 22:30:05,589 >>	[START]  Processor.train()
[INFO] 2019-02-20 22:30:05,590 >>	[START]  PyTorchClassifier.train()
[INFO] 2019-02-20 22:30:05,593 >>		 >> 0 folds start
[INFO] 2019-02-20 22:30:05,593 >>		 	 Generating datasets...
[INFO] 2019-02-20 22:30:05,595 >>		 	 	 Reading train_Kernel02.csv...
[INFO] 2019-02-20 22:30:05,618 >>		 	 	 Reading train_Binary.csv...
[INFO] 2019-02-20 22:31:00,670 >>		 	 	 Reading validate_Kernel02.csv...
[INFO] 2019-02-20 22:31:00,681 >>		 	 	 Reading validate_Binary.csv...
[INFO] 2019-02-20 22:31:14,311 >>		 	 Datasets were generated.
[ERROR] 2019-02-20 22:31:16,318 >>	Unexpected Exception Occurred.
Traceback (most recent call last):
  File "src/main.py", line 23, in <module>
    main(get_option())
  File "src/main.py", line 14, in main
    ProcessorFactory.process(args)
  File "/media/mocobt/Volume/Kaggle/Malware/src/processor_factory.py", line 39, in process
    validity, predict = processor.process()
  File "/media/mocobt/Volume/Kaggle/Malware/src/processor.py", line 42, in process
    validity = None if only_prediction() and model_exist() else self.__train(feature_names)
  File "/media/mocobt/Volume/Kaggle/Malware/src/save_log.py", line 112, in wrapper
    result = func(*args, **kargs)
  File "/media/mocobt/Volume/Kaggle/Malware/src/processor.py", line 69, in __train
    return self.classifier.train(feature_names)
  File "/media/mocobt/Volume/Kaggle/Malware/src/save_log.py", line 112, in wrapper
    result = func(*args, **kargs)
  File "/media/mocobt/Volume/Kaggle/Malware/src/classifier/pytorch_classifier.py", line 90, in train
    verbose=self.params["verbose"])
  File "/media/mocobt/Volume/Kaggle/Malware/src/classifier/torch_util.py", line 75, in train_model
    loss = criterion(outputs, labels)
  File "/home/mocobt/.pyenv/versions/3.6.7/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mocobt/.pyenv/versions/3.6.7/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 504, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/mocobt/.pyenv/versions/3.6.7/lib/python3.6/site-packages/torch/nn/functional.py", line 2027, in binary_cross_entropy
    input, target, weight, reduction_enum)
RuntimeError: reduce failed to synchronize: device-side assert triggered
