[INFO] 2019-01-12 18:18:05,479 >>	[START]  Processor.preprocess()
[INFO] 2019-01-12 18:18:05,480 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 00:24:31,301 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 06:06:25
[INFO] 2019-01-13 00:24:31,303 >>	[START]  FeatureExtractor.extract()
[INFO] 2019-01-13 03:02:21,525 >>	[FINISH] FeatureExtractor.extract(): [elapsed_time] >> 02:37:50
[INFO] 2019-01-13 03:02:21,527 >>	[START]  FeatureExtractor.extract()
[ERROR] 2019-01-13 08:45:23,027 >>	Unexpected Exception Occurred.
KeyboardInterrupt

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/main.py", line 20, in <module>
    main(get_option())
  File "src/main.py", line 12, in main
    ProcessorFactory.process(args)
  File "/home/icebee/project/malware/src/processor_factory.py", line 32, in process
    validity, predict = processor.process()
  File "/home/icebee/project/malware/src/processor.py", line 29, in process
    feature_names = self.__preprocess()
  File "/home/icebee/project/malware/src/save_log.py", line 83, in wrapper
    result = func(*args, **kargs)
  File "/home/icebee/project/malware/src/processor.py", line 45, in __preprocess
    feature_extractor.extract(part="test", valid_dir=valid_dir)
  File "/home/icebee/project/malware/src/save_log.py", line 83, in wrapper
    result = func(*args, **kargs)
  File "/home/icebee/project/malware/src/feature_extractor.py", line 38, in extract
    feature_dict[group] = group_feature_instance.extract()
  File "/home/icebee/project/malware/features/Categorical.py", line 71, in extract
    return super().extract()
  File "/home/icebee/project/malware/features/base_feature.py", line 73, in extract
    self.saveNewFeature(new_feature_df)
  File "/home/icebee/project/malware/features/base_feature.py", line 153, in saveNewFeature
    feature_df.to_csv(self.output_path, index=False)
  File "/home/icebee/.local/share/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pandas/core/frame.py", line 1745, in to_csv
    formatter.save()
  File "/home/icebee/.local/share/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 171, in save
    self._save()
  File "/home/icebee/.local/share/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 286, in _save
    self._save_chunk(start_i, end_i)
  File "/home/icebee/.local/share/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 300, in _save_chunk
    quoting=self.quoting)
  File "/home/icebee/.local/share/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pandas/core/internals.py", line 766, in to_native_types
    values = values.astype(str)
SystemError: <built-in method item of numpy.ndarray object at 0x7ff8ea2eacb0> returned a result with an error set
