[INFO] 2019-02-22 18:26:17,193 >>	Classifier Type: LGBM
[INFO] 2019-02-22 18:26:17,194 >>	Input Path: /home/berry/Malware/data/subset/min
[INFO] 2019-02-22 18:26:17,195 >>	--------------------------------
[INFO] 2019-02-22 18:26:17,196 >>	[START]  Processor.preprocess()
[INFO] 2019-02-22 18:26:17,197 >>	[START]  FeatureExtractor.extract()
[ERROR] 2019-02-22 18:26:18,317 >>	Unexpected Exception Occurred.
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/berry/.pyenv/versions/3.6.6/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/berry/.pyenv/versions/3.6.6/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/berry/.pyenv/versions/3.6.6/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/berry/.pyenv/versions/3.6.6/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/berry/.pyenv/versions/3.6.6/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/berry/Malware/features/base_feature.py", line 58, in calcFratures
    new_feature_df = eval(formula[0], locals())
  File "<string>", line 1, in <module>
  File "/home/berry/Malware/features/Kernel01.py", line 312, in heuristic_SmartScreen_encoding
    assert False
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/main.py", line 23, in <module>
    main(get_option())
  File "src/main.py", line 14, in main
    ProcessorFactory.process(args)
  File "/home/berry/Malware/src/processor_factory.py", line 39, in process
    validity, predict = processor.process()
  File "/home/berry/Malware/src/processor.py", line 41, in process
    feature_names = self.__preprocess()
  File "/home/berry/Malware/src/save_log.py", line 112, in wrapper
    result = func(*args, **kargs)
  File "/home/berry/Malware/src/processor.py", line 51, in __preprocess
    feature_extractor.extract(part="train", valid_dir=valid_dir)
  File "/home/berry/Malware/src/save_log.py", line 112, in wrapper
    result = func(*args, **kargs)
  File "/home/berry/Malware/src/feature_extractor.py", line 38, in extract
    feature_dict[group] = group_feature_instance.extract()
  File "/home/berry/Malware/features/Kernel01.py", line 38, in extract
    return super().extract()
  File "/home/berry/Malware/features/base_feature.py", line 110, in extract
    new_features_list = Parallel(n_jobs=get_njobs())([delayed(calcFratures)(name, formula) for name, formula in needCalculationFeatures.items()])
  File "/home/berry/.pyenv/versions/3.6.6/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/berry/.pyenv/versions/3.6.6/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/berry/.pyenv/versions/3.6.6/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/berry/.pyenv/versions/3.6.6/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/berry/.pyenv/versions/3.6.6/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AssertionError
