[ERROR] 2019-02-22 18:47:49,298 >>	Unexpected Exception Occurred.
Traceback (most recent call last):
  File "src/main.py", line 23, in <module>
    main(get_option())
  File "src/main.py", line 14, in main
    ProcessorFactory.process(args)
  File "/home/berry/Malware/src/processor_factory.py", line 24, in process
    config_file = cls.__load_config(args.version)
  File "/home/berry/Malware/src/processor_factory.py", line 66, in __load_config
    return version_file_list[0]
IndexError: list index out of range
